name: unit test 

on: 
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4

      - name: python setup 
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'
          
      - name: dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: testing 
        run: pytest

